### ISSUE TITLE
InlineKeyboard Buttons under the message

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/inline-keyboard-pagination#4]
Hi!
How to make sure that each page has two buttons?
For example:

**[MESSAGE: id: 1220, name: orange, count: 10]**
_[Contact]_
_[Review]_
**[PAGINATION]**

When the user clicks on the button "Contact" or "Review", the handler starts. For contact: **executeCommand()** _/contact_ and **executeCommand()** _/review1220_ for Review.

Is it hard to do this? :(

Thanks in advance!

**Comment by noplanman** [comment]
Should be easy enough!

Given this example from the readme:
```php
$data['reply_markup' => [
    'inline_keyboard' => [
        $pagination['keyboard'],
    ],
];
```
`$pagination['keyboard']` is basically a row in the keyboard, so you can easily extra rows/buttons before, like this:
```php
$data['reply_markup' => [
    'inline_keyboard' => [
        [['text' => 'Contact', 'callback_data' => 'contact']],
        [['text' => 'Review', 'callback_data' => 'review_1220']],
        $pagination['keyboard'],
    ],
];
```

Give that a try!

(I haven't tested this code, but it *should* work)

**Comment by MyZik** [comment]
@noplanman Oh, I forgot!
Thank you, all works perfectly :)
