### ISSUE TITLE
Can't install & Run it !

### ISSUE THREAD

**Issue by wp098** [php-telegram-bot/inline-keyboard-pagination#6]
Hello and thanks to code this prefect plugin !!

My php version is **7** and I installed and downloaded all contents from composer ( almost **12 Mb** ! )

after that, I uploaded them in host and got them in my code with **autoload.php**

I write this in my code to do : 

```
require_once('vendor/autoload.php');

$items         = range(1, 100);
$command       = 'testCommand'; 
$selected_page = 10;           
$labels        = [              
    'default'  => '%d',
    'first'    => '« %d',
    'previous' => '‹ %d',
    'current'  => '· %d ·',
    'next'     => '%d ›',
    'last'     => '%d »',
];

$callback_data_format = 'command={COMMAND}&oldPage={OLD_PAGE}&newPage={NEW_PAGE}'

$ikp = new InlineKeyboardPagination($items, $command);
$ikp->setMaxButtons(7, true);
$ikp->setLabels($labels);
$ikp->setCallbackDataFormat($callback_data_format);

$pagination = $ikp->getPagination($selected_page);
$ikp->setSelectedPage($selected_page);
$pagination = $ikp->getPagination();

if (!empty($pagination['keyboard'])) {
telegram_sendmessage( $USERID, 'TESTing ...', $pagination['keyboard'] );	
}

```

But action doesn't work and I get this error in **error.log**  : 

> PHP Parse error:  syntax error, unexpected '$ikp' (T_VARIABLE) in ...

**Comment by noplanman** [comment]
Could you send the whole error message please?

Clearly you're using that variable somewhere where it hasn't been defined.

**Comment by wp098** [comment]
Thank you, Fixed 🥇
